- root/etc/cont-init.d/30-config
> linting fix

- Dockerfile
- README.md
> switch to using inhouse mono baseimage

- Dockerfile-builder
> build for 16.04, copy additional files into zip

- Dockerfile
- README.md
> Update port to default 5000

- Dockerfile
- root/etc/cont-init.d/30-config
- root/etc/services.d/ombi/run
> Auto update ombi on restart, define user data location

- README.md
- root/etc/services.d/ombi/run
> Change port to 3579

- Dockerfile
> Change home folder to /config

- Dockerfile
- README.md
- root/etc/cont-init.d/30-config
> Pull DotNetCore branch artifact

- Dockerfile
- README.md
- root/etc/cont-init.d/30-config
> Ignore pr build artifacts when updating

- Dockerfile
- README.md
> fix continuation lines

- Dockerfile
- README.md
> add HOME env to Dockerfile

- README.md
- root/etc/cont-init.d/90-config
> Deprecate preview

- Jenkinsfile
- jenkins-vars.yml
We get a 404 code, but it returns the correct version.
> intentionally using the wrong file endpoint to get version number 

- README.md
- readme-vars.yml
> #30 minor readme update

- README.md
- readme-vars.yml
> add info on tags and development builds

- README.md
- readme-vars.yml
> add info on tags and development branch

- README.md
- readme-vars.yml
> use the new readme layout for tags

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- jenkins-vars.yml
> fix version check

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- jenkins-vars.yml
> don't build PRs

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
- root/etc/cont-init.d/30-config
New asset ingestion point for their development head for v4. 
Need some light testing as I am not 100% on the chown change but I do not see any cache directories in there.
> pull assets from github repo and drop netcore app chowning

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
Change in format of downloaded file.
> tarballs no longer have embedded zip

- .github/workflows/external_trigger.yml
- .github/workflows/external_trigger_scheduler.yml
- .github/workflows/package_trigger.yml
- .github/workflows/package_trigger_scheduler.yml
- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
When merged, disable the following jenkins triggers:
https://ci.linuxserver.io/job/External-Triggers/job/ombi-external-trigger/
https://ci.linuxserver.io/job/External-Triggers/job/Package-Triggers/job/ombi-package-trigger/
> update maintainer, add trigger workflows

- .github/workflows/external_trigger.yml
- .github/workflows/package_trigger.yml
When merged, disable the following jenkins triggers:
https://ci.linuxserver.io/job/External-Triggers/job/Package-Triggers/job/ombi-development-package-trigger/
https://ci.linuxserver.io/job/External-Triggers/job/ombi-development-external-trigger/
> add trigger workflows

- .github/workflows/external_trigger.yml
- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- jenkins-vars.yml
- readme-vars.yml
Ombi is transitioning to a organization, the v4 builds are the first to move.
Builds and run latest v4 release
> Update link for releases

- .github/workflows/external_trigger.yml
- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
Copied requirements from v4-preview, updated urls
v4
Built locally on amd64 and set up a dummy instance.
> First attempt to move preview to v4

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- readme-vars.yml
- root/etc/cont-init.d/30-config
- root/etc/services.d/ombi/run
> Rebase master to Jammy

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- readme-vars.yml
- root/etc/cont-init.d/30-config
- root/etc/services.d/ombi/run
> Rebase development to Jammy

- root/etc/s6-overlay/s6-rc.d/svc-ombi/run
> Exec notify
